# Generated by Django 4.2.5 on 2023-10-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacture',
            old_name='type',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='manufacture',
            name='gender',
        ),
        migrations.AddField(
            model_name='manufacture',
            name='place',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacture',
            name='post',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
