# Generated by Django 4.2.5 on 2023-10-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_type_manufacture_pin_rename_type_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='status',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
