# Generated by Django 4.2.5 on 2023-10-18 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_manufacture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='MANUFACTURE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.manufacture'),
            preserve_default=False,
        ),
    ]
