# Generated by Django 4.2.5 on 2023-10-18 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category_manufacture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('MANUFACTURE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.manufacture')),
            ],
        ),
    ]
